### ISSUE TITLE
linux host + virtualization with qemu

### ISSUE THREAD

**Issue by r4s3cl3** [b00t0x/ROG-Zephyrus-G14-GA402-Hackintosh#27]
Have you tried a linux host such as ubuntu or fedora, and using virtmanager to vmake a vm, and also looking glass kvm solution? You will have all functionalities working with the linux host and you will passtrough the gpu to your macos VM

**Comment by b00t0x** [comment]
I have considered using Proxmox, but I did not think it would be practical for the following reasons.
* RDNA 2 GPU may not working due to vendor-reset issue.
* I don't know how to passthrough I2C Trackpad and battery status.

And I have not thought virtualization with GUI host. Looking Glass doesn't seem to be available on macOS.
